/**
 * Harit Kapadia, Jack Farley
 * Ms. Krasteva
 * 2019/June/02
 */

public enum BlockKey {
        GROUND, WATER, POISON, TREE, HOGWEED, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE, 
                DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY, FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM, 
                STRAWBERRIES
}
