public enum BlockKey {
        GROUND, WATER, POISON, TREE, HOGWEED, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE, 
                DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY, FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM, 
                STRAWBERRIES
}
