/**
 * Harit Kapadia, Jack Farley
 * Ms. Krasteva
 * 2019/June/02
 */

/**
 * An enum to store the block names
 */
public enum BlockKey {
        GROUND, WATER, POISON, TREE, HOGWEED, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE,
                DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY, FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM,
                STRAWBERRIES, KNIFE, ANT, GRASSHOPPER, WORM, FLINTSTEEL, FIRE, WATERBOTTLE, PALISADE, BED, CATTAIL, WATERPURIFICATIONTABLETS
}
