/**
 * Harit Kapadia, Jack Farley
 * Ms. Krasteva
 * 2019/June/02
 */

public enum ItemKey {
        KNIFE, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE, DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY,
                FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM, STRAWBERRIES, ANT, GRASSHOPPER, WORM
}
