public enum ItemKey {
        KNIFE, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE, DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY,
                FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM, STRAWBERRIES
}
