/**
 * Harit Kapadia, Jack Farley
 * Ms. Krasteva
 * 2019/June/02
 */

/**
 * Enum storing all the item names
 */
public enum ItemKey {
	KNIFE, WOOD, KINGBOLETE, NORTHERNBLUEFLAG, FLYAGARIC, CHANTERELLE, DESTROYINGANGEL, FLINT, BEDSTRAW, ELDERBERRY,
		FIDDLEHEADS, INDIANPIPE, MOONSEED, MOREL, MUSHROOM, STRAWBERRIES, ANT, GRASSHOPPER, WORM, FLINTSTEEL,
	FIRE, WATERBOTTLE, CATTAIL
}
